version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.10-browsers
    steps:
      - checkout
      - restore_cache:
          key: jard
      - run:
          name: Maven build and test
          command: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar spring-boot:build-image -Dsonar.projectKey=njuro_jard
      - sonarcloud/scan
      - run:
          name: Remove jard files from cache
          command: rm -rf ~/.m2/repository/com/github/njuro
      - save_cache:
          key: jard
          paths:
            - ~/.m2
      - run:
          name: Deploy to docker hub
          command: bash docker_push.sh
workflows:
  default:
    jobs:
      - build:
          context: jard